### ISSUE TITLE
MBB board rev 3, firmware 24 outputs unexpected values in log start / end byte addresses

### ISSUE THREAD

**Issue by CrashCash** [KimBurgess/zero-log-parser#2]
I got the latest code from here, and it has this error stack:

Parsing 538SM7Z36FCG04513_MBB_2016-02-28.bin...
8730 entries found
Traceback (most recent call last):
  File "./zero_log_parser.py", line 257, in <module>
    parse_log(log_file, output_file)
  File "./zero_log_parser.py", line 229, in parse_log
    (length, entry) = parse_entry(log, read_pos)
  File "./zero_log_parser.py", line 76, in parse_entry
    header = log.unpack('char', 0x0, offset=address)
  File "./zero_log_parser.py", line 66, in unpack
    count=count)
  File "./zero_log_parser.py", line 48, in unpack
    return struct.unpack_from(type_format, buff, address)[0]
struct.error: unpack_from requires a buffer of at least 1 bytes

[538SM7Z36FCG04513_MBB_2016-02-28.bin.zip](https://github.com/KimBurgess/zero-log-parser/files/150085/538SM7Z36FCG04513_MBB_2016-02-28.bin.zip)

**Comment by kimburgess** [comment]
Awesome, thanks for the report! I've just had a look at the attached log file and the bytes that hold where I'd normally expect to see addresses for the first and last log entries contain a value that is out of range for that file (and identical). It looks like I may have misinterpreted something, or things have changes between firmware revs. This is going to require a little more digging...

**Comment by CrashCash** [comment]
Thanks for taking a look. As usual, my bike is strange. :-)

**Comment by CrashCash** [comment]
FYI, the Android app updated, and now gives you the ability to download either the "motorcycle" or "battery" logs, or both. I did "both" and it gave me 3 files:

05:48:42 ~/motorcycle/zero-sr/logs/temp $ ../zero_log_parser.py 538SM7Z36FCG04513_MBB_2016-03-06.bin 
Parsing 538SM7Z36FCG04513_MBB_2016-03-06.bin...
8776 entries found
Traceback (most recent call last):
  File "../zero_log_parser.py", line 257, in <module>
    parse_log(log_file, output_file)
  File "../zero_log_parser.py", line 229, in parse_log
    (length, entry) = parse_entry(log, read_pos)
  File "../zero_log_parser.py", line 79, in parse_entry
    length = log.unpack('uint8', 0x1, offset=address)
  File "../zero_log_parser.py", line 66, in unpack
    count=count)
  File "../zero_log_parser.py", line 48, in unpack
    return struct.unpack_from(type_format, buff, address)[0]
struct.error: unpack_from requires a buffer of at least 1 bytes
05:48:57 ~/motorcycle/zero-sr/logs/temp # ../zero_log_parser.py 538SM7Z36FCG04513_BMS0_2016-03-06.bin 
Parsing 538SM7Z36FCG04513_BMS0_2016-03-06.bin...
9512 entries found
Traceback (most recent call last):
  File "../zero_log_parser.py", line 257, in <module>
    parse_log(log_file, output_file)
  File "../zero_log_parser.py", line 229, in parse_log
    (length, entry) = parse_entry(log, read_pos)
  File "../zero_log_parser.py", line 78, in parse_entry
    raise ValueError('Invalid entry header byte')
ValueError: Invalid entry header byte
05:49:08 ~/motorcycle/zero-sr/logs/temp # ../zero_log_parser.py 538SM7Z36FCG04513_BMS1_2016-03-06.bin 
Parsing 538SM7Z36FCG04513_BMS1_2016-03-06.bin...
1549 entries found
Traceback (most recent call last):
  File "../zero_log_parser.py", line 257, in <module>
    parse_log(log_file, output_file)
  File "../zero_log_parser.py", line 229, in parse_log
    (length, entry) = parse_entry(log, read_pos)
  File "../zero_log_parser.py", line 78, in parse_entry
    raise ValueError('Invalid entry header byte')
ValueError: Invalid entry header byte

Let me know if you want copies. (198K zipped)

**Comment by crewsdaniel** [comment]
I got a similar error ... its not a fatal error at least. Script runs well for my use. Thanks for putting this out.

**Comment by mattkav** [comment]
Thanks for developing this!  Unfortunately, I have the same issue as CrashCash.  (I tried all 3 files, too.)  Let me know if you want my files to help debug.
