### ISSUE TITLE
Invalid entry header byte

### ISSUE THREAD

**Issue by brayhead** [KimBurgess/zero-log-parser#6]
Hi there,
first of all thanks for the script! It worked fine the first time I used it (log1.bin).
Some days later I exported my bike logs again (log2.bin), but the script came up with following:
```
Parsing log2.bin...
8252 entries found
Traceback (most recent call last):
  File "zero_log_parser.py", line 566, in <module>
    parse_log(log_file, output_file)
  File "zero_log_parser.py", line 538, in parse_log
    (length, entry) = parse_entry(event_log, read_pos)
  File "zero_log_parser.py", line 98, in parse_entry
    raise ValueError('Invalid entry header byte')
ValueError: Invalid entry header byte
```
I have tried the bug-fix suggested in the other issue, but that fix only cam up with:

```
  File "zero_log_parser2.py", line 99
    print 'Skipped %d bytes for alignment' % address
                                         ^
SyntaxError: Missing parentheses in call to 'print'
```
Are you still working on bug fixes?
Cheers,
brayhead

>>> sorry, can't upload .zip files - will have to check out why that is... <<<

**Comment by brayhead** [comment]
I have downloaded the bike logs again (in exactly same way) and now the script works just fine. Strange?!?
